import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import idxStyles from '../styles/index.module.css'
import logo from '../src/images/logo.svg'
import placeholder from '../src/images/imgPlaceholder.svg'
import phoneCenter from '../src/images/phone-center.png'
import phoneRight from '../src/images/phone-right.png'
import phoneLeft from '../src/images/phone-left.png'
import Spline from '@splinetool/react-spline';
import { animateScroll as scroll } from 'react-scroll'
import { scrollToTop } from 'react-scroll/modules/mixins/animate-scroll'
import { InlineWidget } from "react-calendly";


const goToHome = () => {
  scroll.scrollToTop();
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JPG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
        <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
      </Head>

      <main className={styles.main}>



        <div className={idxStyles.headerContainer}>
          <line className={idxStyles.headerLine} />
          <Image src={logo} onClick={goToHome} alt="JPG Logo" width={200} height={120} />
          <line className={idxStyles.headerLine} />
        </div>

        {/* <div className={idxStyles.phoneContainer}>
          <Spline scene="https://prod.spline.design/9cnB2x9Y2g6nW3jf/scene.splinecode" />
        </div> */}

        <div className={idxStyles.mainGrid}>
          <div className={idxStyles.grid1}>
            <p>
              We Bring Customers To Our Clients <br />
              Through Social Media Marketing.<br />
              With an Incredible <span className={idxStyles.highlightFont}>ROI</span>
            </p>
          </div>

          <div className={idxStyles.grid1}>
            <Image src={phoneRight} alt="JPG Logo" width={300} height={600} />
          </div>

        </div>






        {/* STAT STRIP----------------------------------------------------------------------------------------------------------------- */}
        <div className={idxStyles.gridBorder}>
          <div className={idxStyles.mainGrid}>

            <div className={idxStyles.gridNumbers}>
              <p> 4 <br /><span className={idxStyles.highlightFont}>active clients</span> </p>

            </div>
            <div className={idxStyles.gridNumbers}>
              <p>$580.00 <br /><span className={idxStyles.highlightFont}>Monthly AD Spend</span> </p>

            </div>
            <div className={idxStyles.gridNumbers}>
              <p>4.2 × <br /><span className={idxStyles.highlightFont}>Average ROI</span> </p>

            </div>

          </div>
        </div>
        {/* STAT STRIP----------------------------------------------------------------------------------------------------------------- */}









        {/* HOW WE OPERATE----------------------------------------------------------------------------------------------------------------- */}
        <div className={idxStyles.mainGrid2}>
          <div className={idxStyles.grid2}>
            <Image src={phoneLeft} alt="JPG Logo" width={300} height={600} />
          </div>
          <div className={idxStyles.opGrid}>
            <div className={idxStyles.grid2}>
              <h2 className={`${idxStyles.highlightFont} ${idxStyles.titleFlexStart}`} >How We Operate</h2>
              <p>
                We analyse the history of your brand.<br /><br />
                We craft a strategy that is in harmony with your brand vision<br /><br />
                We create & run campaigns that sell your product efficiently.<br /><br />
                We collect & utilize data to continuously optimise & scale your campaigns.<br /><br />
                We always strive to achieve a ROI of 4+ for our clients
              </p>
            </div>
            <div className={idxStyles.grid2}>
              <h2 className={`${idxStyles.highlightFont} ${idxStyles.titleFlexStart}`}>How We Don't Operate</h2>
              <p>
                We do not create the content for campaigns<br /><br />
                We do not offer google ads, email marketing or SEO Optimization<br /><br />
                We do not charge money to onboard you<br /><br />
                We do not offer free trials
              </p>
            </div>
          </div>
          {/* HOW WE OPERATE----------------------------------------------------------------------------------------------------------------- */}




        </div>
        <div className={idxStyles.mainGrid}>
          <div className={idxStyles.opGrid}>
            <div className={idxStyles.grid2}>
              <h2 className={`${idxStyles.highlightFont} ${idxStyles.titleFlexStart}`}>Next Gen Agency</h2>
              <p>
                We know how the old-fashioned agency works. Month-long on-boarding processes, high start-up fees,
                poor communication, and finally; the lack of pace.
                <span className={idxStyles.highlightFont}> JPG Agency </span>
                is a new breed of agency. We’ll spend less than an hour on-boarding you,
                and then we skip straight to strategizing and delivering results. You’ll be surprised by our efficiency.
                This is possible because of the Seamless Systems we’ve developed.
                These systems allow for breathtaking results, frequent,
                in-depth & easy-to-understand performance reports, a rapid workflow,
                and prices based on logic instead of guesswork. At JPG Agency everything feels seamless.
                We put our clients first. We’ll handle the boring logistics,
                while you enjoy superior results being generated on a daily basis.
              </p>
            </div>
          </div>
          <div className={idxStyles.grid1}>
            <Image src={phoneRight} alt="JPG Logo" width={300} height={600} />
          </div>
        </div>






        {/* data-url="https://calendly.com/jpgagency/strategy-meeting?text_color=070d20&primary_color=ffde59" */}

        {/* calendar ---------------------------------------------------------------------------------------------------------------- */}





        <div className={idxStyles.mainGrid}>
          <div className={idxStyles.grid2}>
            <div className={idxStyles.calendar}>



              <div className={idxStyles.calendarContainer}>
                <InlineWidget url="https://calendly.com/jpgagency/strategy-meeting?hide_event_type_details=1&hide_gdpr_banner=1&background_color=070d20&text_color=ffffff&primary_color=ffde59" />
              </div>

              <Image className={idxStyles.calendarPhoneContainer} src={phoneCenter} alt="JPG Logo" width={400} height={800} />
              

            </div>

          </div>
          <div className={idxStyles.opGrid}>
            <div className={idxStyles.grid2}>
              <h2 className={`${idxStyles.highlightFont} ${idxStyles.titleFlexStart}`}>Book A Free Strategy Call</h2>
              <p>
                We know how the old-fashioned agency works. Month-long on-boarding processes, high start-up fees, poor communication, and finally; the lack of pace.

                Stage Digital is a new breed of agency. We’ll spend less than an hour on-boarding you, and then we skip straight to strategizing and delivering results. You’ll be surprised by our efficiency. This is possible because of the Seamless Systems we’ve developed. These systems allow for breathtaking results, frequent, in-depth & easy-to-understand performance reports, a rapid workflow, and prices based on logic instead of guesswork. At Stage Digital everything feels seamless. We put our clients first.

                We’ll handle the boring logistics, while you enjoy superior results being generated on a daily basis.
              </p>
              <h2 className={`${idxStyles.highlightFont} ${idxStyles.titleFlexStart}`}>This Strategy Call Is Particularly For:</h2>
              <p>
                Businesses looking to increase their online sales with a breathtaking return on investment.<br /><br />
                Businesses looking to optimise their social media marketing efforts in conjunction with the leading agency in the industry.<br /><br />
                Businesses looking for an agency that can take them from mediocre to superior within the field of eCommerce & Online Sales.<br /><br />
                Businesses looking for an agency that has no higher priority than the clients it serves.<br /><br />
                “We shall always divert our best brains to achieve succes for our existing clients, instead of to the pursuit of new clients”
              </p>
            </div>
          </div>
        </div>



        {/* calendar ---------------------------------------------------------------------------------------------------------------- */}

      </main>



      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo.svg" width={72} height={55} />
          </span>
        </a>
      </footer>
    </div>
  )
}
